### ISSUE TITLE
How we are going to handle the decimal of the tokens ?

### ISSUE THREAD

**Issue by satyamakgec** [WandXDapp/WandX-Options#3]
We have functions which taking the asset quantity as the parameter on that same parameter basis we are dealing with `transfer` and `transferFrom` function but those functions need value in terms of desirable decimal of that token. 
https://github.com/WandXDapp/WandX-Options/blob/e8083bdcabd80accab2a4582b39b1427afcebdd6/contracts/Option.sol#L134-L144

For sorting this issue I am only entertaining 18 decimal as hard-coded value. If anyone has any more solutions to handle decimals then please share your thoughts.

**Comment by abhinavramesh** [comment]
Can we check which Token it is, and get the decimal places from the Token there? Since some Tokens which are quite popular, have 6 decimal points or some other number for decimal points.

**Comment by satyamakgec** [comment]
I think not, In the contract because we are using Interface that has the ERC20 standard functions and in that, there is no function from which we get the decimal value. But if we try to resolve this problem using frontend then we can. Only we need 2 arguments extra in the createOption function, one for baseToken decimal and another for the quoteToken decimal.

**Comment by abhinavramesh** [comment]
Yes, we can resolve it from Front-end. You can assign it to Seshadri for the front-end.

**Comment by satyamakgec** [comment]
ok, I will assign to Seshadri

**Comment by satyamakgec** [comment]
@bssrdev  assign to you

**Comment by satyamakgec** [comment]
fixed on UI end
