### ISSUE TITLE
How to dump the assets that are sold by the seller ?

### ISSUE THREAD

**Issue by satyamakgec** [WandXDapp/WandX-Options#6]
We need to destroy the assets that are sold back by the seller at the time of `exerciseOption`.
Current situation I am using the OptionDumper contract to collect all the sold assets and at the time of withdrawal of the tokens by the writer or buyer, OptionDumper got self-destruct. 
__Pros__ - No direct handling of balances mapping. It uses transferFrom function that helps the exchanges to watch the `Transfer` event.
__Cons__ - one extra contract gets created that increase the gas consumption.

If you all agree with this way then we can go in that way otherwise the option is below.
We can directly reduce the balance from the `balances` mapping and decrease the `assetOffered` public variable value. This is same as we handle the burning of the token situation.  
__Pros__ - the user doesn't need to do an extra transaction for allowance. 
__Cons__ - It looks like a burning transaction not the buyback transaction.

**Comment by abhinavramesh** [comment]
Let's go with the first option as its closer to what actually happens.

**Comment by ksridharbabuus** [comment]
My suggestion is not self destruct instead have logical permanent kill where we track the overall trade of options.

Logical kill means -> have a flag to indicate it is completed and no more actions can be performed except the reading metadata about the option like when it is created, enabled, executed, exercised and so on... This will help us to get more metrics...

**Comment by satyamakgec** [comment]
I think dumper contract doesn't give us any type of metrics or data because it is already a waste contract we are using to transfer the assets to it only because we can't transfer the ERC20 asset to `0x0` address.
